{
 "title": "metrics-ms-launcher-api",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
    }
   },
   {
    "name": "pool",
    "label": "pool",
    "query": {
     "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  { "title": "API BASIC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UPTIME",
   "type": "stat",
   "description": "API uptime",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\"}"
    }
   ]
  },
  {
   "title": "JDBC POOL",
   "type": "stat",
   "description": "Pool de conexões JDBC",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", pool=\"HikariPool-1\"}"
    }
   ]
  },
  {
   "title": "CONNECTION STATE",
   "type": "timeseries",
   "description": "Estado das conexões com o database",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", pool=\"HikariPool-1\"}",
     "legendFormat": "active"
    },
    {
     "expr": "hikaricp_connections_idle{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", pool=\"HikariPool-1\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "hikaricp_connections_pending{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", pool=\"HikariPool-1\"}",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "START TIME",
   "type": "stat",
   "description": "Hora da inicialização da API",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\"} * 1000"
    }
   ]
  },
  {
   "title": "DB CONNECTION TIMEOUT",
   "type": "stat",
   "description": "Conexões com o database em timeout",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hikaricp_connections_timeout_total{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", pool=\"HikariPool-1\"}[1m])"
    }
   ]
  },
  {
   "title": "WARN & ERROR LOG",
   "type": "timeseries",
   "description": "Warnings e erros logados nos últimos 5 minutos",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(logback_events_total{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", level=\"error\"}[5m]))",
     "legendFormat": "erro"
    },
    {
     "expr": "sum(increase(logback_events_total{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\",level=\"warn\"}[5m]))",
     "legendFormat": "warn"
    }
   ]
  },
  { "title": "API USE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "HEAP USED",
   "type": "gauge",
   "description": "Memória heap utilizada",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\",area=\"heap\"})* 100 / sum(jvm_memory_max_bytes{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\",area=\"heap\"})"
    }
   ]
  },
  {
   "title": "CPU UTILIZATION",
   "type": "timeseries",
   "description": "Utilização de CPU",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"ms-launcher\",instance=\"host.docker.internal:8080\", job=\"ms-launcher\"}",
     "legendFormat": "Process CPU usage"
    }
   ]
  },
  {
   "title": "NON-HEAP USED",
   "type": "gauge",
   "description": "Memória non-heap utilizada ",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", area=\"nonheap\"})* 100 / sum(jvm_memory_max_bytes{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "LOAD AVERAGE",
   "type": "timeseries",
   "description": "Média de uso de CPU",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\"}",
     "legendFormat": "Load average [1m]"
    }
   ]
  },
  { "title": "API RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "TOTAL REQUESTS",
   "type": "stat",
   "description": "Total de requisições no último minuto",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\"}[1m]))"
    }
   ]
  },
  {
   "title": "ERROR 500",
   "type": "stat",
   "description": "Número de erros 500 no último minuto",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", status=\"500\"}[1m]))"
    }
   ]
  },
  {
   "title": "LATENCY AVERAGE",
   "type": "timeseries",
   "description": "Latência média por minuto",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri!~\"/\\\\*\\\\*|/actuator/health/\\\\*\\\\*|/actuator/metrics/\\\\{requiredMetricName\\\\}|/swagger-ui\\\\*/\\\\*\\\\*|/actuator|/actuator/health|/actuator/info|/actuator/prometheus|/v3/api-docs|/v3/api-docs/swagger-config\"}[1m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri!~\"/\\\\*\\\\*|/actuator/health/\\\\*\\\\*|/actuator/metrics/\\\\{requiredMetricName\\\\}|/swagger-ui\\\\*/\\\\*\\\\*|/actuator|/actuator/health|/actuator/info|/actuator/prometheus|/v3/api-docs|/v3/api-docs/swagger-config\"}[1m])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri!~\"/\\\\*\\\\*|/actuator/health/\\\\*\\\\*|/actuator/metrics/\\\\{requiredMetricName\\\\}|/swagger-ui\\\\*/\\\\*\\\\*|/actuator|/actuator/health|/actuator/info|/actuator/prometheus|/v3/api-docs|/v3/api-docs/swagger-config\"}[1m])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri!~\"/\\\\*\\\\*|/actuator/health/\\\\*\\\\*|/actuator/metrics/\\\\{requiredMetricName\\\\}|/swagger-ui\\\\*/\\\\*\\\\*|/actuator|/actuator/health|/actuator/info|/actuator/prometheus|/v3/api-docs|/v3/api-docs/swagger-config\"}[1m])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(http_server_requests_seconds_bucket{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri!~\"/\\\\*\\\\*|/actuator/health/\\\\*\\\\*|/actuator/metrics/\\\\{requiredMetricName\\\\}|/swagger-ui\\\\*/\\\\*\\\\*|/actuator|/actuator/health|/actuator/info|/actuator/prometheus|/v3/api-docs|/v3/api-docs/swagger-config\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "ERROR RATE",
   "type": "timeseries",
   "description": "Taxa de erros nos últimos 5 minutos",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\",status=\"500\", uri!~\"/\\\\*\\\\*|/actuator/health/\\\\*\\\\*|/actuator/metrics/\\\\{requiredMetricName\\\\}|/swagger-ui\\\\*/\\\\*\\\\*|/actuator|/actuator/health|/actuator/info|/actuator/prometheus|/v3/api-docs|/v3/api-docs/swagger-config\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri!~\"/\\\\*\\\\*|/actuator/health/\\\\*\\\\*|/actuator/metrics/\\\\{requiredMetricName\\\\}|/swagger-ui\\\\*/\\\\*\\\\*|/actuator|/actuator/health|/actuator/info|/actuator/prometheus|/v3/api-docs|/v3/api-docs/swagger-config\"}[5m]))",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\",status=\"400\", uri!~\"/\\\\*\\\\*|/actuator/health/\\\\*\\\\*|/actuator/metrics/\\\\{requiredMetricName\\\\}|/swagger-ui\\\\*/\\\\*\\\\*|/actuator|/actuator/health|/actuator/info|/actuator/prometheus|/v3/api-docs|/v3/api-docs/swagger-config\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri!~\"/\\\\*\\\\*|/actuator/health/\\\\*\\\\*|/actuator/metrics/\\\\{requiredMetricName\\\\}|/swagger-ui\\\\*/\\\\*\\\\*|/actuator|/actuator/health|/actuator/info|/actuator/prometheus|/v3/api-docs|/v3/api-docs/swagger-config\"}[5m]))",
     "legendFormat": "400"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\",status=\"404\", uri!~\"/\\\\*\\\\*|/actuator/health/\\\\*\\\\*|/actuator/metrics/\\\\{requiredMetricName\\\\}|/swagger-ui\\\\*/\\\\*\\\\*|/actuator|/actuator/health|/actuator/info|/actuator/prometheus|/v3/api-docs|/v3/api-docs/swagger-config\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri!~\"/\\\\*\\\\*|/actuator/health/\\\\*\\\\*|/actuator/metrics/\\\\{requiredMetricName\\\\}|/swagger-ui\\\\*/\\\\*\\\\*|/actuator|/actuator/health|/actuator/info|/actuator/prometheus|/v3/api-docs|/v3/api-docs/swagger-config\"}[5m]))",
     "legendFormat": "404"
    }
   ]
  },
  {
   "title": "RESPONSE TIME",
   "type": "timeseries",
   "description": "Tempo de resposta da API no último minuto",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri!~\"/\\\\*\\\\*|/actuator/health/\\\\*\\\\*|/actuator/metrics/\\\\{requiredMetricName\\\\}|/swagger-ui\\\\*/\\\\*\\\\*|/actuator|/actuator/health|/actuator/info|/actuator/prometheus|/v3/api-docs|/v3/api-docs/swagger-config\"}[1m]) / rate(http_server_requests_seconds_count{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri!~\"/\\\\*\\\\*|/actuator/health/\\\\*\\\\*|/actuator/metrics/\\\\{requiredMetricName\\\\}|/swagger-ui\\\\*/\\\\*\\\\*|/actuator|/actuator/health|/actuator/info|/actuator/prometheus|/v3/api-docs|/v3/api-docs/swagger-config\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    }
   ]
  },
  {
   "title": "REQUEST COUNT",
   "type": "timeseries",
   "description": "Número de requisições por endpoint no último minuto",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri=\"/v1/persons\", method=\"GET\"}[1m]))",
     "legendFormat": "/v1/persons - GET"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri=\"/v1/persons/{id}\", method=\"GET\"}[1m]))",
     "legendFormat": "/v1/persons/{id} - GET"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri=\"/v1/persons\", method=\"POST\"}[1m]))",
     "legendFormat": "/v1/persons - POST"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri=\"/v1/persons/{id}\", method=\"PUT\"}[1m]))",
     "legendFormat": "/v1/persons/{id} - PUT"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri=\"/v1/persons/{id}\", method=\"DELETE\"}[1m]))",
     "legendFormat": "/v1/persons/{id} - DELETE"
    }
   ]
  },
  {
   "title": "AVERAGE REQUEST DURATION",
   "type": "timeseries",
   "description": "Duração média de requisições no último minuto",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri=\"/v1/persons\", method=\"GET\"}[1m]) / rate(http_server_requests_seconds_count{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri=\"/v1/persons\", method=\"GET\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri=\"/v1/persons/{id}\", method=\"GET\"}[1m]) / rate(http_server_requests_seconds_count{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri=\"/v1/persons/{id}\", method=\"GET\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri=\"/v1/persons\", method=\"POST\"}[1m]) / rate(http_server_requests_seconds_count{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri=\"/v1/persons\", method=\"POST\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri=\"/v1/persons/{id}\", method=\"PUT\"}[1m]) / rate(http_server_requests_seconds_count{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri=\"/v1/persons/{id}\", method=\"PUT\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri=\"/v1/persons/{id}\", method=\"DELETE\"}[1m]) / rate(http_server_requests_seconds_count{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri=\"/v1/persons/{id}\", method=\"DELETE\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    }
   ]
  },
  {
   "title": "MAX REQUEST DURATION",
   "type": "timeseries",
   "description": "Duração máxima de uma requisição",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{application=\"ms-launcher\", instance=\"host.docker.internal:8080\", job=\"ms-launcher\", uri!~\"/\\\\*\\\\*|/actuator/health/\\\\*\\\\*|/actuator/metrics/\\\\{requiredMetricName\\\\}|/swagger-ui\\\\*/\\\\*\\\\*|/actuator|/actuator/health|/actuator/info|/actuator/prometheus|/v3/api-docs|/v3/api-docs/swagger-config\"}"
    }
   ]
  }
 ]
}